import type { AccountType } from '@/lib/product/accountTypes'

export const FEATURE_KEYS = [
  'deals',
  'rent_analysis',
  'market_rent',
  'section8_hud',
  'brrrr',
  'flip',
  'wholesale',
  'seller_finance',
  'five_year_projection',
  'csv_export',
  'pdf_export',
  'buyers',
  'buyer_matching',
  'deal_distribution',
  'community_members',
  'white_label',
  'ai_review',
  'lender_view',
  'admin_plan_management',
] as const

export type FeatureKey = (typeof FEATURE_KEYS)[number]
export type FeatureMap = Partial<Record<FeatureKey, boolean>>
export type LimitMap = Record<string, number | null>

export const featureLabels: Record<FeatureKey, string> = {
  deals: 'Deals / Properties',
  rent_analysis: 'Rent Analysis',
  market_rent: 'Market Rent',
  section8_hud: 'Section 8 / HUD',
  brrrr: 'BRRRR Calculator',
  flip: 'Fix & Flip Calculator',
  wholesale: 'Wholesale Calculator',
  seller_finance: 'Seller Finance',
  five_year_projection: '5-Year Projection',
  csv_export: 'CSV Export',
  pdf_export: 'PDF Export',
  buyers: 'Buyer CRM',
  buyer_matching: 'Buyer Matching',
  deal_distribution: 'Deal Distribution',
  community_members: 'Community Members',
  white_label: 'White Label',
  ai_review: 'AI Deal Review',
  lender_view: 'Bank / Lender View',
  admin_plan_management: 'Admin Plan Management',
}

export const accountTypeDefaultFeatures: Record<AccountType, FeatureMap> = {
  solo_investor: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: true,
    brrrr: true,
    flip: true,
    wholesale: true,
    five_year_projection: true,
    csv_export: true,
    lender_view: true,
  },
  wholesaler: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    wholesale: true,
    flip: true,
    buyers: true,
    buyer_matching: true,
    deal_distribution: true,
    csv_export: true,
  },
  landlord: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: false,
    brrrr: false,
    flip: false,
    wholesale: false,
    five_year_projection: true,
    csv_export: true,
    lender_view: true,
  },
  section_8_landlord: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: true,
    brrrr: false,
    flip: false,
    wholesale: false,
    five_year_projection: true,
    csv_export: true,
    lender_view: true,
  },
  brrrr_investor: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: true,
    brrrr: true,
    flip: false,
    wholesale: false,
    five_year_projection: true,
    csv_export: true,
    lender_view: true,
  },
  fix_and_flip_investor: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    brrrr: false,
    flip: true,
    wholesale: true,
    five_year_projection: false,
    csv_export: true,
  },
  community_guru_owner: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: true,
    brrrr: true,
    flip: true,
    wholesale: true,
    five_year_projection: true,
    csv_export: true,
    buyers: true,
    buyer_matching: true,
    deal_distribution: true,
    community_members: true,
    white_label: true,
    lender_view: true,
  },
  team_company: {
    deals: true,
    rent_analysis: true,
    market_rent: true,
    section8_hud: true,
    brrrr: true,
    flip: true,
    wholesale: true,
    five_year_projection: true,
    csv_export: true,
    buyers: true,
    buyer_matching: true,
    deal_distribution: true,
    lender_view: true,
  },
}

export function mergeFeatures(...featureMaps: Array<FeatureMap | null | undefined>): FeatureMap {
  return featureMaps.reduce<FeatureMap>((acc, map) => ({ ...acc, ...(map || {}) }), {})
}

export function canUseFeature(features: FeatureMap | null | undefined, feature: FeatureKey) {
  return Boolean(features?.[feature])
}
